#ifndef GRAPHDIALOG_H
#define GRAPHDIALOG_H

#include <iostream>
#include <QDialog>
#include <QColor>
#include <QPalette>
#include <QTabWidget>
#include <QFontDialog>
#include <QColorDialog>
#include <iostream>

#include "ui_graphstyle.h"
#include "qcustomplot.h"

class GraphDialog : public QDialog
{
    Q_OBJECT

public:
    GraphDialog(QWidget *parent =0);
    
    void setGraph(QCPGraph * graph);
    void updateGraph(QCPGraph * graph = NULL);

private slots:

    void _setGraphColor(QColor color);
    void _setGraphStyle(bool checked);
    void _updateInterface();


private:
    
    // graphical user interface generated by QT Designer
    Ui::Graphstyle _ui;

    // pointer to the graph which will be changed
    QCPGraph *_graph;
    
    // item for style like lsStepLeft, lsStepRight, etc...
    QCPGraph::LineStyle _line_style;
    
    // items for QCPScatterStyle( ScatterShape  shape, const QPen &  pen, const QBrush &  brush, double  size  ) 
    QCPScatterStyle::ScatterShape _marker_shape;
    QPen _marker_pen;
    QBrush _marker_brush;
    double _marker_size;
    double _marker_width;
    
    // properties of the line
    QPen _line_pen;
    double _line_width;
};

#endif // GRAPHDIALOG_H


